package com.edutech.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CursoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCursoAllPropertiesEquals(Curso expected, Curso actual) {
        assertCursoAutoGeneratedPropertiesEquals(expected, actual);
        assertCursoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCursoAllUpdatablePropertiesEquals(Curso expected, Curso actual) {
        assertCursoUpdatableFieldsEquals(expected, actual);
        assertCursoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCursoAutoGeneratedPropertiesEquals(Curso expected, Curso actual) {
        assertThat(actual)
            .as("Verify Curso auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCursoUpdatableFieldsEquals(Curso expected, Curso actual) {
        assertThat(actual)
            .as("Verify Curso relevant properties")
            .satisfies(a -> assertThat(a.getNome()).as("check nome").isEqualTo(expected.getNome()))
            .satisfies(a -> assertThat(a.getDescricao()).as("check descricao").isEqualTo(expected.getDescricao()))
            .satisfies(a -> assertThat(a.getCargaHoraria()).as("check cargaHoraria").isEqualTo(expected.getCargaHoraria()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCursoUpdatableRelationshipsEquals(Curso expected, Curso actual) {
        assertThat(actual)
            .as("Verify Curso relationships")
            .satisfies(a -> assertThat(a.getProfessor()).as("check professor").isEqualTo(expected.getProfessor()));
    }
}
