package com.edutech.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InscricaoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInscricaoAllPropertiesEquals(Inscricao expected, Inscricao actual) {
        assertInscricaoAutoGeneratedPropertiesEquals(expected, actual);
        assertInscricaoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInscricaoAllUpdatablePropertiesEquals(Inscricao expected, Inscricao actual) {
        assertInscricaoUpdatableFieldsEquals(expected, actual);
        assertInscricaoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInscricaoAutoGeneratedPropertiesEquals(Inscricao expected, Inscricao actual) {
        assertThat(actual)
            .as("Verify Inscricao auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInscricaoUpdatableFieldsEquals(Inscricao expected, Inscricao actual) {
        assertThat(actual)
            .as("Verify Inscricao relevant properties")
            .satisfies(a -> assertThat(a.getDataInscricao()).as("check dataInscricao").isEqualTo(expected.getDataInscricao()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInscricaoUpdatableRelationshipsEquals(Inscricao expected, Inscricao actual) {
        assertThat(actual)
            .as("Verify Inscricao relationships")
            .satisfies(a -> assertThat(a.getAluno()).as("check aluno").isEqualTo(expected.getAluno()))
            .satisfies(a -> assertThat(a.getCurso()).as("check curso").isEqualTo(expected.getCurso()));
    }
}
